[package]
name = "network_limiter"
version = "0.1.0"
edition = "2021"

[dependencies]
ndisapi = "0.6.0"
windows = { version = "0.58.0" , features = ["Win32_Foundation", "Win32_System_Threading", "Win32_Security"] }
